name: Creati Studio Video Creator

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Creati Studio Email'
        required: true
      password:
        description: 'Creati Studio Password'
        required: true
      productDescription:
        description: 'Product Description'
        required: true
      productImageUrl:
        description: 'Product Image URL'
        required: true

jobs:
  create-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm' # npm paketlerini cache'leyerek sonraki çalıştırmaları hızlandırır
        
    - name: Install Dependencies and Browsers
      run: |
        # package-lock.json dosyasından hızlı ve tutarlı kurulum yapar
        npm ci 
        # ANA DÜZELTME: --with-deps bayrağı ile sistem bağımlılıklarını kurar
        npx playwright install --with-deps chromium
      
    - name: Run automation script
      run: node creati-automation.mjs
      env:
        EMAIL: ${{ github.event.inputs.email }}
        PASSWORD: ${{ secrets.PASSWORD }} # Güvenlik için şifreyi secret olarak saklamak daha iyidir
        DESCRIPTION: ${{ github.event.inputs.productDescription }}
        IMAGE_URL: ${{ github.event.inputs.productImageUrl }}
    
    - name: Upload debug screenshots
      uses: actions/upload-artifact@v4
      # 'always()' sayesinde script hata verse bile ekran görüntüleri yüklenir
      if: always()
      with:
        name: debug-screenshots
        path: "*.png"
        retention-days: 1
