name: Creati Studio Video Creator

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Creati Studio Email'
        required: true
      password:
        description: 'Creati Studio Password'
        required: true
      productDescription:
        description: 'Product Description'
        required: true
      productImageUrl:
        description: 'Product Image URL'
        required: true

jobs:
  create-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Dependencies and Browser
      run: |
        # Geçici bir package.json oluştur ve Playwright'i kur
        npm init -y
        npm pkg set type=module
        npm install playwright
        
        # ANA DÜZELTME BURASI: --with-deps bayrağı, tarayıcının çalışması için 
        # gereken tüm sistem kütüphanelerini (fontlar, grafik kütüphaneleri vb.) kurar.
        npx playwright install --with-deps chromium
      
    - name: Run automation script
      run: node creati-automation.mjs
      env:
        # ÖNEMLİ GÜVENLİK NOTU: Gerçek projelerde şifrenizi workflow_dispatch
        # ile girmek yerine, GitHub Repository Secrets kısmına ekleyip
        # `PASSWORD: ${{ secrets.YOUR_SECRET_NAME }}` olarak kullanmanız çok daha güvenlidir.
        EMAIL: ${{ github.event.inputs.email }}
        PASSWORD: ${{ github.event.inputs.password }}
        DESCRIPTION: ${{ github.event.inputs.productDescription }}
        IMAGE_URL: ${{ github.event.inputs.productImageUrl }}
    
    - name: Upload debug screenshots
      uses: actions/upload-artifact@v4
      # 'always()' sayesinde script hata verse bile ekran görüntüleri yüklenir
      if: always()
      with:
        name: debug-screenshots
        path: "*.png"
        retention-days: 1
