# Hibrit Creati AI Otomasyonu - N8N Entegrasyonu
name: Creati AI Hybrid Automation

on:
  workflow_dispatch:
    inputs:
      productDescription:
        description: 'Ürün açıklaması (Google Sheets\'ten)'
        required: true
        type: string
      productImageUrl:
        description: 'Ürün görsel URL\'si (Google Sheets\'ten)'
        required: true
        type: string
      email:
        description: 'Creati Studio email'
        required: true
        type: string
  repository_dispatch:
    types: [n8n-creati-trigger]

jobs:
  hybrid-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        npm init -y
        npm pkg set type=module
        npm install playwright
        npx playwright install --with-deps chromium
      
    - name: Extract inputs
      run: |
        if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
          echo "DESCRIPTION=${{ github.event.client_payload.productDescription }}" >> $GITHUB_ENV
          echo "IMAGE_URL=${{ github.event.client_payload.productImageUrl }}" >> $GITHUB_ENV
          echo "EMAIL=${{ github.event.client_payload.email }}" >> $GITHUB_ENV
        else
          echo "DESCRIPTION=${{ github.event.inputs.productDescription }}" >> $GITHUB_ENV
          echo "IMAGE_URL=${{ github.event.inputs.productImageUrl }}" >> $GITHUB_ENV
          echo "EMAIL=${{ github.event.inputs.email }}" >> $GITHUB_ENV
        fi
      
    - name: Validate inputs
      run: |
        if [[ -z "$DESCRIPTION" ]] || [[ -z "$IMAGE_URL" ]] || [[ -z "$EMAIL" ]]; then
          echo "Eksik input parametresi"
          exit 1
        fi
        echo "Inputs doğrulandı:"
        echo "Açıklama uzunluğu: $(echo "$DESCRIPTION" | wc -c)"
        echo "Görsel URL: $IMAGE_URL"
        echo "Email: $EMAIL"
      
    - name: Automation Info
      run: |
        echo "HİBRİT OTOMASYON BAŞLIYOR"
        echo "=========================="
        echo "Bu otomasyon şu adımları içerir:"
        echo "1. Otomatik login"
        echo "2. Templates sayfasına git"  
        echo "3. MANUEL: Template seçimi (90 saniye)"
        echo "4. Otomatik: Upload + form + generate"
        echo ""
        echo "MANUEL ADIM NEDENİ:"
        echo "Template seçimi en karmaşık kısım olduğu için"
        echo "90 saniye manuel süre verilir. Bu sürede:"
        echo "- Template seçin"
        echo "- Use/Create butonuna basın"
        echo "- Upload sayfasına ilerleyin"
        echo ""
      
    - name: Run Hybrid Automation
      run: node creati-automation.mjs
      env:
        EMAIL: ${{ env.EMAIL }}
        PASSWORD: ${{ secrets.CREATI_STUDIO_PASSWORD }}
        DESCRIPTION: ${{ env.DESCRIPTION }}
        IMAGE_URL: ${{ env.IMAGE_URL }}
        PLAYWRIGHT_BROWSERS_PATH: '/home/runner/.cache/ms-playwright'
    
    - name: Upload debug files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: hibrit-debug-${{ github.run_number }}
        path: |
          *.png
          *.html
          *.log
        retention-days: 5
        
    - name: Success notification
      if: success()
      run: |
        echo "HİBRİT OTOMASYON BAŞARILI"
        echo "Video oluşturma süreci başlatıldı"
        
        # n8n success webhook
        if [[ -n "${{ secrets.N8N_SUCCESS_WEBHOOK }}" ]]; then
          curl -X POST "${{ secrets.N8N_SUCCESS_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d '{
              "status": "success",
              "message": "Hibrit otomasyon başarılı",
              "runId": "${{ github.run_number }}",
              "productDescription": "'"$DESCRIPTION"'",
              "imageUrl": "'"$IMAGE_URL"'",
              "automationType": "hybrid"
            }' || echo "Success webhook hatası"
        fi
          
    - name: Failure notification  
      if: failure()
      run: |
        echo "HİBRİT OTOMASYON BAŞARISIZ"
        
        # n8n error webhook
        if [[ -n "${{ secrets.N8N_ERROR_WEBHOOK }}" ]]; then
          curl -X POST "${{ secrets.N8N_ERROR_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d '{
              "status": "error", 
              "message": "Hibrit otomasyon başarısız",
              "runId": "${{ github.run_number }}",
              "productDescription": "'"$DESCRIPTION"'",
              "imageUrl": "'"$IMAGE_URL"'",
              "automationType": "hybrid"
            }' || echo "Error webhook hatası"
        fi

    - name: Manual Step Guidance
      if: failure()
      run: |
        echo "MANUEL ADIM REHBERİ"
        echo "==================="
        echo "Eğer hata manuel adımda olduysa:"
        echo "1. Daha fazla süre verin (90 saniye yeterli değilse)"
        echo "2. Template seçimini hızlandırın"
        echo "3. 'Use' butonunu bulup tıklamayı unutmayın"
        echo "4. Upload sayfasına kadar ilerleyin"
        echo ""
        echo "Debug için screenshot'ları kontrol edin."
