# Workflow'un adı
name: Creati Studio Video Creator

# Workflow'un ne zaman tetikleneceğini belirler.
on:
  workflow_dispatch:
    # Manuel çalıştırma sırasında kullanıcıdan istenecek girdiler
    inputs:
      email:
        description: 'Creati Studio Email'
        required: true
        type: string
      productDescription:
        description: 'Product Description'
        required: true
        type: string
      productImageUrl:
        description: 'Product Image URL'
        required: true
        type: string

# Workflow'un içereceği işler (jobs)
jobs:
  create-video:
    # Job'un çalışacağı sanal makine tipi
    runs-on: ubuntu-latest
    
    # Job'un adımları (steps)
    steps:
    # 1. Adım: Kod reposunu sanal makineye indirir
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # 2. Adım: Node.js ortamını kurar
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    # 3. Adım: Gerekli NPM paketlerini ve Playwright tarayıcısını kurar
    - name: Install Dependencies and Browser
      run: |
        npm init -y
        npm pkg set type=module
        npm install playwright
        # --with-deps bayrağı, GitHub Actions ortamı için gerekli tüm sistem kütüphanelerini kurar.
        npx playwright install --with-deps chromium
      
    # 4. Adım: Otomasyon betiğini çalıştırır
    - name: Run automation script
      run: node creati-automation.mjs
      env:
        # workflow_dispatch ile alınan girdileri ortam değişkeni olarak betiğe aktarıyoruz
        EMAIL: ${{ github.event.inputs.email }}
        # --- GÜVENLİK GÜNCELLEMESİ ---
        # Şifre artık GitHub Secrets'tan güvenli bir şekilde alınıyor.
        # Bu secret'ı reponuzun Ayarlar (Settings) kısmından eklemelisiniz.
        PASSWORD: ${{ secrets.CREATI_STUDIO_PASSWORD }}
        DESCRIPTION: ${{ github.event.inputs.productDescription }}
        IMAGE_URL: ${{ github.event.inputs.productImageUrl }}
    
    # 5. Adım: Hata ayıklama için oluşturulan ekran görüntülerini bir artifact olarak kaydeder
    - name: Upload debug screenshots
      # 'if: always()' sayesinde, önceki adımlar hata verse bile bu adım her zaman çalışır.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshots
        path: "*.png"
        retention-days: 1
